ZUTOOLS={};ZUTOOLS.LayoutManager=function(){var a=this;this.toolbar=new ZUTOOLS.Toolbar;this.separator=new ZUTOOLS.Separator(this);this.webgl=new ZUTOOLS.WebGL;this.status=new ZUTOOLS.Status;this.controls=new ZUTOOLS.Controls;this.tabbar=new ZUTOOLS.Tabbar;this.width=window.innerWidth;this.height=window.innerHeight;this.columns=[];this.setColumns(0,this.width/10);this.setColumns(1,this.width/50);this.setSizes();window.addEventListener("resize",function(){var b=window.innerWidth;a.setColumns(0,a.columns[0]/a.width*
b);a.setColumns(1,a.columns[1]/a.width*b);a.width=b;a.height=window.innerHeight;a.setSizes()},!1)};
ZUTOOLS.LayoutManager.prototype={constructor:ZUTOOLS.LayoutManager,setSizes:function(){var a=Math.min(Math.max(this.columns[0],40),this.width/3),b=Math.min(Math.max(this.columns[1],5),40),c=this.width,d=this.height;this.toolbar.setSize(a+1,d+1);this.separator.setSize(b+1,d+1,a);this.webgl.setSize(c-a-b+1,d+1,a+b);this.controls.setSize(c-a-b+1,d+1,a+b);this.tabbar.setSize(c-a-b+1,d+1,a+b);this.status.setSize(c,d+1,a+b)},setColumns:function(a,b){this.columns[a]=Math.max(0.1,b)},confinedSum:function(){var a=
Math.min(Math.max(this.columns[0],40),this.width/3),b=Math.min(Math.max(this.columns[1],5),40);return a+b},addTab:function(a,b){this.tabbar.addTab(a,b);this.setSizes()}};ZUTOOLS.Separator=function(a){var b=this;this.parent=a;this.div=document.createElement("div");this.div.style.position="absolute";this.div.style.top="0px";this.div.setAttribute("class","action col");document.body.appendChild(this.div);this.leftStart=this.left=void 0;this.resizeActive=!1;this.resizeStart=void 0;this.div.addEventListener("mousedown",function(a){b.leftStart=b.left;b.resizeStart=a.clientX;b.resizeActive=!0},!1);document.addEventListener("mousemove",function(a){b.resizeActive&&(b.parent.setColumns(0,
b.leftStart+a.clientX-b.resizeStart),b.parent.setSizes())},!1);document.addEventListener("mouseup",function(){b.resizeActive=!1},!1);document.addEventListener("selectstart",function(a){a.preventDefault();a.stopPropagation()},!1)};ZUTOOLS.Separator.prototype={constructor:ZUTOOLS.Separator,setSize:function(a,b,c){this.div.style.width=a+"px";this.div.style.height=b+"px";this.left=c;this.div.style.left=c+"px"}};ZUTOOLS.Toolbar=function(){this.height=this.width=void 0;this.div=document.createElement("div");this.div.style.position="absolute";this.div.style.top="0px";this.div.style.left="0px";this.div.style.background="#3d9ecb";document.body.appendChild(this.div);this.svg=document.createElementNS(ZUSE.SVGUtils.NS,"svg");this.svg.setAttribute("xmlns:xlink",ZUSE.SVGUtils.XLink);this.svg.setAttribute("width","100%");this.svg.setAttribute("height","100%");this.div.appendChild(this.svg);this.svg.appendChild(ZUSE.XMLUtils.loadXML("images/tool.svg").documentElement.firstElementChild.nextElementSibling);
this.tools=[];this.toolsByName={}};
ZUTOOLS.Toolbar.prototype={constructor:ZUTOOLS.Toolbar,setSize:function(a,b){this.width=a;this.height=b;this.div.style.width=a+"px";this.div.style.height=b+"px";this.shuffle()},shuffle:function(){for(var a=this.width-1,b=this.height-1,c=this.tools.length,d=1,e=24*(b/(24*Math.ceil(c/d)+2));e*d+e+2<=a;)d++,e=24*(b/(24*Math.ceil(c/d)+2));a=Math.min(a/(d+1/12),e);for(b=0;b<this.tools.length;b++)this.tools[b].setSize(a,1+24*(b%d),1+24*Math.floor(b/d))},addTool:function(a,b,c,d,e){a=new ZUTOOLS.Tool(this,
b,c,d,e);this.tools.push(a);this.toolsByName[b]=a;this.shuffle();return a}};ZUTOOLS.WebGL=function(){function a(){requestAnimationFrame(a);b.camera.controls.update();b.renderer.render(b.scene,b.camera);TWEEN.update()}var b=this;this.div=document.createElement("div");this.div.style.position="absolute";this.div.style.top="0px";this.div.style.background="#fff";document.body.appendChild(this.div);this.renderer=new THREE.WebGLRenderer({antialias:!0});this.div.appendChild(this.renderer.domElement);this.scene=new THREE.Scene;this.camera=new THREE.PerspectiveCamera(50,1,1,2500);
this.camera.controls=new ZUSE.CameraControls(this.camera,this.renderer.domElement);this.camera.controls.reset();this.scene.add(this.camera);a()};
ZUTOOLS.WebGL.prototype={constructor:ZUTOOLS.WebGL,setSize:function(a,b,c){this.div.style.width=a+"px";this.div.style.height=b+"px";this.div.style.left=c+"px";this.camera.aspect=a/b;this.camera.updateProjectionMatrix();this.renderer.setSize(a,b);this.camera.controls.screen.width=a;this.camera.controls.screen.height=b;this.camera.controls.screen.offsetLeft=c;this.camera.controls.radius=(a+b)/4}};ZUTOOLS.Tool=function(a,b,c,d,e){var g=this;this.activatable=d;this.disabled=this.activated=!1;this.events=c;a.svg.appendChild(ZUSE.XMLUtils.loadXML("images/icons/"+b+".svg").documentElement.firstElementChild.nextElementSibling.nextElementSibling);this.group=document.createElementNS(ZUSE.SVGUtils.NS,"g");this.group.setAttribute("class","tool");a.svg.appendChild(this.group);a=document.createElementNS(ZUSE.SVGUtils.NS,"title");e=document.createTextNode(e);a.appendChild(e);this.group.appendChild(a);
this.rectangle=document.createElementNS(ZUSE.SVGUtils.NS,"use");this.rectangle.setAttributeNS(ZUSE.SVGUtils.XLink,"href","#tool");this.group.appendChild(this.rectangle);this.icon=document.createElementNS(ZUSE.SVGUtils.NS,"use");this.icon.setAttributeNS(ZUSE.SVGUtils.XLink,"href","#"+b);this.icon.setAttribute("fill","#f5f3e5");this.icon.setAttribute("stroke","none");this.group.appendChild(this.icon);this.tick=document.createElementNS(ZUSE.SVGUtils.NS,"use");this.tick.setAttributeNS(ZUSE.SVGUtils.XLink,
"href","#tick");this.tick.setAttribute("class","tick");this.tick.style.visibility="hidden";this.group.appendChild(this.tick);this.group.addEventListener("click",function(){g.disabled||(g.activatable&&g.switchActivation(),g.events.click())},!1);c.mouseover&&this.group.addEventListener("mouseover",c.mouseover,!1);c.mouseout&&this.group.addEventListener("mouseout",c.mouseout,!1)};
ZUTOOLS.Tool.prototype={constructor:ZUTOOLS.Tool,setSize:function(a,b,c){this.group.setAttribute("transform","scale("+a/24+") translate("+b+","+c+")")},switchActivation:function(){this.activated=!this.activated;this.showActivation(this.activated);return this},showActivation:function(a){this.tick.style.visibility=a?"visible":"hidden"},disable:function(a){this.disabled=void 0===a?!0:a;this.group.setAttribute("class",this.disabled?"toolDisabled":"tool");this.tick.setAttribute("class",this.disabled?"tickDisabled":
"tick")}};ZUTOOLS.Controls=function(){var a=this;this.expanded=!0;this.bigger=!1;this.div=document.createElement("div");this.div.style.position="absolute";this.div.style.top="10px";this.div.style.width="270px";document.body.appendChild(this.div);this.title=document.createElement("div");this.title.innerHTML="Z1 Adder";this.title.setAttribute("class","controltitle action topcorners pointer");this.title.style.padding="8px";this.div.appendChild(this.title);this.title.addEventListener("click",function(){a.switchExpanded()},
!1);this.input=document.createElement("div");this.input.style.background="#ddd";this.div.appendChild(this.input);this.svg=document.createElementNS(ZUSE.SVGUtils.NS,"svg");this.svg.setAttribute("xmlns:xlink",ZUSE.SVGUtils.XLink);this.svg.setAttribute("viewBox","0, 0, 180, 100");this.svg.setAttribute("width","270px");this.svg.setAttribute("height","150px");this.svg.style.display="block";this.input.appendChild(this.svg);var b=document.createElementNS(ZUSE.SVGUtils.NS,"line");b.setAttribute("x1",10);
b.setAttribute("x2",108);b.setAttribute("y1",68);b.setAttribute("y2",68);b.setAttribute("class","line");this.svg.appendChild(b);b=document.createElementNS(ZUSE.SVGUtils.NS,"line");b.setAttribute("x1",126);b.setAttribute("x2",170);b.setAttribute("y1",68);b.setAttribute("y2",68);b.setAttribute("class","line");this.svg.appendChild(b);this.scale=document.createElement("div");this.scale.setAttribute("class","action bottomcorners pointer");this.scale.style.height="10px";this.div.appendChild(this.scale);
this.scale.addEventListener("click",function(){a.expanded?(a.bigger=!a.bigger,a.div.style.width=a.bigger?"450px":"270px",a.svg.setAttribute("width",a.bigger?"450px":"270px"),a.svg.setAttribute("height",a.bigger?"250px":"150px")):a.switchExpanded()},!1)};
ZUTOOLS.Controls.prototype={constructor:ZUTOOLS.Controls,setSize:function(a,b,c){this.div.style.left=c+10+"px"},switchExpanded:function(){this.expanded=!this.expanded;this.input.style.display=this.expanded?"block":"none"},addDigit:function(a,b,c,d){return new ZUTOOLS.Digit(this.svg,a,b,c,d)}};ZUTOOLS.Digit=function(a,b,c,d,e){function g(){f.input&&f.setValue(f.events.click())}function h(){f.show&&f.events.mouseover()}function i(){f.show&&f.events.mouseout()}var f=this;this.events=e;this.input=this.show=!1;this.group=document.createElementNS(ZUSE.SVGUtils.NS,"g");this.group.setAttribute("transform","translate("+b+","+c+")");this.group.setAttribute("class","digit");a.appendChild(this.group);this.events&&(a=document.createElementNS(ZUSE.SVGUtils.NS,"rect"),a.setAttribute("rx",d?2:4),a.setAttribute("ry",
d?2:4),a.setAttribute("width",d?"9px":"18px"),a.setAttribute("height",d?"12px":"24px"),this.group.appendChild(a),this.events.click&&this.group.addEventListener("click",g,!1),this.events.mouseover&&this.events.mouseout&&(this.group.addEventListener("mouseover",h,!1),this.group.addEventListener("mouseout",i,!1)));a=document.createElementNS(ZUSE.SVGUtils.NS,"text");a.setAttribute("x",d?1.5:3);a.setAttribute("y",d?10:20);a.setAttribute("class","inputText");a.style.fontSize=d?"10px":"20px";a.setAttributeNS("http://www.w3.org/XML/1998/namespace",
"xml:space","preserve");this.group.appendChild(a);this.textNode=document.createTextNode("");a.appendChild(this.textNode)};
ZUTOOLS.Digit.prototype={constructor:ZUTOOLS.Digit,setToEmpty:function(){this.textNode.nodeValue="";this.setShow(!1);return this},setToZero:function(){this.textNode.nodeValue="0";this.setShow(!0);return this},setToOne:function(){this.textNode.nodeValue="1";this.setShow(!0);return this},setToPlus:function(){this.textNode.nodeValue="+";this.setShow(!1);return this},setText:function(a){this.textNode.nodeValue=a;this.setShow(!1);return this},setValue:function(a){void 0!==a&&(a?this.setToOne():this.setToZero());
return this},inputOn:function(){this.setInput(!0);return this},inputOff:function(){this.setInput(!1);return this},setShow:function(a){this.show=a;this.setClass()},setInput:function(a){this.input=a;this.setClass()},setClass:function(){this.input?this.group.setAttribute("class","digitInput"):this.show?this.group.setAttribute("class","digitShow"):this.group.setAttribute("class","digit")}};ZUTOOLS.Tabbar=function(){this.div=document.createElement("div");this.div.style.position="absolute";document.body.appendChild(this.div);this.tabs=[]};ZUTOOLS.Tabbar.prototype={constructor:ZUTOOLS.Tabbar,setSize:function(a,b,c){this.div.style.top=b+"px";this.div.style.left=c+10+"px";for(a=c=0;a<this.tabs.length;a++)c=this.tabs[a].setPosition(c)},addTab:function(a,b){var c=new ZUTOOLS.Tab(this,a,b);this.tabs.push(c)},closeAll:function(){for(var a=0;a<this.tabs.length;a++)this.tabs[a].close()}};ZUTOOLS.Tab=function(a,b,c){var d=this;this.parent=a;this.expanded=!1;this.title=document.createElement("div");this.title.style.position="absolute";this.title.setAttribute("class","action topcorners");this.title.style.padding="8px";this.title.style.cursor="pointer";this.title.innerHTML=b;this.title.style.zIndex=2;a.div.appendChild(this.title);this.closer=document.createElement("div");this.closer.style.position="absolute";this.closer.setAttribute("class","closer");this.closer.style.padding="8px";this.closer.style.cursor=
"pointer";this.closer.innerHTML=b;this.closer.style.zIndex=1;a.div.appendChild(this.closer);this.content=document.createElement("div");this.content.style.position="absolute";this.content.style.top="0px";this.content.style.left="0px";this.content.style.display="none";this.content.setAttribute("class","topborder greybox bigpadding");this.content.appendChild(c);a.div.appendChild(this.content);this.title.addEventListener("click",function(){d.switchExpanded()},!1);this.closer.addEventListener("click",
function(){d.close()},!1)};
ZUTOOLS.Tab.prototype={constructor:ZUTOOLS.Tab,setPosition:function(a){this.setPositionTop();this.title.style.left=a+"px";this.closer.style.left=a+"px";return a+this.title.offsetWidth+2},setPositionTop:function(){this.expanded?(this.title.style.top=-this.content.offsetHeight-this.title.offsetHeight+"px",this.content.style.top=-this.content.offsetHeight+"px"):(this.title.style.top=-this.title.offsetHeight+"px",this.content.style.top="0px");this.closer.style.top=-this.title.offsetHeight+"px"},close:function(){this.expanded=
!1;this.content.style.display="none";this.setPositionTop()},open:function(){this.expanded=!0;this.content.style.display="block";this.setPositionTop()},switchExpanded:function(){this.expanded?this.close():(this.parent.closeAll(),this.open())}};ZUTOOLS.Status=function(){this.div=document.createElement("div");this.div.style.position="absolute";document.body.appendChild(this.div);this.states=[];this.addState("1. Input");this.addState("2. Compute Carryover");this.addState("3. Compute Result");this.addState("4. Reset");this.activate(0)};
ZUTOOLS.Status.prototype={constructor:ZUTOOLS.Status,setSize:function(a,b){this.div.style.top=b-110+"px";this.div.style.left=a-260+"px"},addState:function(a){var b=document.createElement("div");b.innerHTML=a;b.setAttribute("class","stat");this.div.appendChild(b);this.states.push(b)},activate:function(a){for(var b=0;b<this.states.length;b++)this.states[b].setAttribute("class","stat");this.states[a].setAttribute("class","stat statActive")}};
